# git
alias g='git'
alias ga='git add'
alias gau='git add -u; git status'
alias gb='git branch'
alias gc='git commit -S'
alias gcm='git commit -S -m'
alias gca='git commit -S --amend'
alias gcadate='git commit -S --amend --date="$(date -R)"'
alias gsh='git show'
alias gd='git diff --ws-error-highlight=old'
alias gcl='git clone'
alias gds='git diff --staged --ws-error-highlight=old'
alias gl='git log'
alias gst='git status'
alias gaa='git add :/; git status'
alias gch='git checkout'
alias gpo='git push origin'
alias gpom='git push origin master; git status'
alias gpothis='echo Push to branch: $(git branch | sed -n -e "s/^\* \(.*\)/\1/p"); git push origin $(git branch | sed -n -e "s/^\* \(.*\)/\1/p")'
alias gsync='git checkout master; git pull upstream master; git push origin master; git checkout -'
alias gpum='git pull upstream master'

# django
alias djpro='django-admin startproject'
alias djrun='python manage.py runserver'
alias djmake='python manage.py makemigrations'
alias djshow='python manage.py showmigrations'
alias djmigrate='python manage.py migrate'
alias djapp='python manage.py startapp'
alias djsuper='python manage.py createsuperuser'
alias djshell='python manage.py shell'
alias djcheck='python manage.py check'
alias djmessage='python manage.py makemessages'

# system
alias cl='clear; source ~/.extra' # to sustain geeky signature
alias shut='shutdown now'
alias afk='systemctl suspend'
alias away='systemctl hibernate'
